/**
 * night.fun — Transaction Builder
 *
 * Implements the real DApp Connector API transaction flow:
 *   1. Build unproven contract call (using compiled contract bindings)
 *   2. Generate ZK proof via provingProvider
 *   3. Balance transaction (add DUST fee payment via wallet)
 *   4. Submit transaction
 *
 * Reference: https://docs.midnight.network/api-reference/dapp-connector
 */

import type { ConnectedAPI } from '@midnight-ntwrk/dapp-connector-api';
import {
  getBuyQuote, getSellQuote,
  type BondingCurveState,
} from '@/lib/midnight/bondingCurve';

// ── Contract bindings ─────────────────────────────────────────────────────────
// Generated by: compact compile contracts/bonding_curve.compact contracts/managed/bonding_curve
// After compilation, import like:
//   import { Contract } from '../../contracts/managed/bonding_curve/contract/index.cjs';
//   import { createBuyTx, createSellTx } from '../../contracts/managed/bonding_curve/contract/index.cjs';

// ── ZK Key Provider ───────────────────────────────────────────────────────────
// Keys are generated by the Compact compiler and served from your Next.js app
// The prover downloads them to generate proofs locally (or delegates to proof server)

function getKeyMaterialUrl(): string {
  return process.env.NEXT_PUBLIC_APP_URL
    ? `${process.env.NEXT_PUBLIC_APP_URL}/zkconfig`
    : '/zkconfig';
}

// ── Buy tokens ────────────────────────────────────────────────────────────────

export interface BuyParams {
  contractAddress: string;
  adaIn:           bigint;     // gross tDUST
  slippageBps:     bigint;
  currentState:    BondingCurveState;
  walletAPI:       ConnectedAPI;
}

export interface TradeResult {
  txHash:    string;
  amountIn:  bigint;
  amountOut: bigint;
}

export async function executeBuy(params: BuyParams): Promise<TradeResult> {
  const { contractAddress, adaIn, slippageBps, currentState, walletAPI } = params;

  const quote  = getBuyQuote(adaIn, currentState.adaReserve, currentState.tokenReserve);
  const minOut = quote.amountOut - (quote.amountOut * slippageBps / 10_000n);

  console.log('[executeBuy]', {
    adaIn: adaIn.toString(),
    expectedOut: quote.amountOut.toString(),
    minOut: minOut.toString(),
    priceImpact: `${quote.priceImpact.toFixed(2)}%`,
  });

  // ── REAL FLOW ──────────────────────────────────────────────────────────────
  //
  // import { FetchZkConfigProvider } from '@midnight-ntwrk/midnight-js-fetch-zk-config-provider';
  // import { Contract } from '../../contracts/managed/bonding_curve/contract/index.cjs';
  //
  // 1. Get service config from wallet (respects user's node/prover settings)
  // const config = await walletAPI.getConfiguration();
  //
  // 2. Set up ZK key provider (fetches proving keys from your static file server)
  // const keyProvider = new FetchZkConfigProvider(getKeyMaterialUrl());
  //
  // 3. Build the unproven contract call transaction
  // const unprovenTx = await buildContractCall({
  //   contractAddress,
  //   entryPoint: 'buy',
  //   args: { ada_in: adaIn, min_tokens: minOut },
  //   nodeUri: config.substrateNodeUri,
  // });
  //
  // 4. Prove it locally (or via wallet's proving provider)
  // const costModel = await fetchCostModel(config.indexerUri);
  // const provingProvider = walletAPI.getProvingProvider(keyProvider);
  // const provenTx = await unprovenTx.prove(provingProvider, costModel);
  //
  // 5. Balance (wallet adds DUST fee input)
  // const { tx: balancedTx } = await walletAPI.balanceUnsealedTransaction(provenTx);
  //
  // 6. Submit
  // const txHash = await walletAPI.submitTransaction(balancedTx);
  //
  // return { txHash, amountIn: adaIn, amountOut: quote.amountOut };
  // ──────────────────────────────────────────────────────────────────────────

  throw new Error(
    'Contract bindings not yet wired. Run: compact compile contracts/bonding_curve.compact'
  );
}

// ── Sell tokens ───────────────────────────────────────────────────────────────

export interface SellParams {
  contractAddress: string;
  tokensIn:        bigint;
  slippageBps:     bigint;
  currentState:    BondingCurveState;
  walletAPI:       ConnectedAPI;
}

export async function executeSell(params: SellParams): Promise<TradeResult> {
  const { contractAddress, tokensIn, slippageBps, currentState, walletAPI } = params;

  const quote  = getSellQuote(tokensIn, currentState.adaReserve, currentState.tokenReserve);
  const minOut = quote.amountOut - (quote.amountOut * slippageBps / 10_000n);

  // Same flow as buy, entryPoint: 'sell', args: { tokens_in: tokensIn, min_ada: minOut }
  throw new Error('Contract bindings not yet wired.');
}

// ── Deploy bonding curve (frontend flow) ──────────────────────────────────────

export interface LaunchTokenParams {
  nameHash:        Uint8Array;
  tickerHash:      Uint8Array;
  descriptionHash: Uint8Array;
  imageHash:       Uint8Array;
  treasuryKeyHex:  string;
  initialBuy:      bigint;
  walletAPI:       ConnectedAPI;
}

export async function launchToken(params: LaunchTokenParams): Promise<{ contractAddress: string; txHash: string }> {
  // Same pattern: build deploy tx → prove → balance → submit
  // entryPoint: constructor
  // args: { creator_sk, treasury_key, name_h, ticker_h, description_h, image_h, initial_ada }
  throw new Error('Contract bindings not yet wired.');
}

// ── Cost model fetcher ────────────────────────────────────────────────────────
//
// The cost model lives in the Indexer GraphQL response under Block.ledgerParameters
// https://github.com/midnightntwrk/midnight-indexer/blob/main/indexer-api/graphql/schema-v3.graphql#L36

export async function fetchCostModel(indexerUri: string): Promise<unknown> {
  const res = await fetch(indexerUri, {
    method:  'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      query: `
        query {
          block {
            ledgerParameters
          }
        }
      `,
    }),
  });

  const data = await res.json() as {
    data?: { block?: { ledgerParameters: unknown } }
  };
  return data?.data?.block?.ledgerParameters ?? null;
}
