'use client';

import Link from 'next/link';

const STEPS = [
  {
    num: '1',
    title: 'Pick a coin or create your own',
    desc: 'Anyone can launch a token in seconds. No presale, no insiders, no team allocation. Just pick a name, ticker, and image — your token is live instantly on a bonding curve.',
  },
  {
    num: '2',
    title: 'Buy on the bonding curve',
    desc: 'The price starts near zero and rises as people buy. Early buyers get the best price. Every trade is settled on-chain with Midnight\'s ZK proofs — fully verifiable, fully private.',
  },
  {
    num: '3',
    title: 'Sell anytime',
    desc: 'There\'s always liquidity. The bonding curve guarantees you can sell your tokens back at any time. No waiting for buyers, no locked liquidity — instant settlement.',
  },
  {
    num: '4',
    title: 'Token graduates at 320,000 NIGHT',
    desc: 'When the bonding curve reserve hits 320,000 NIGHT (~$15K), the token graduates. Liquidity is deposited to NorthStar DEX and LP tokens are burned — making the pool permanent and unruggable.',
  },
];

const FEATURES = [
  {
    title: 'Zero-knowledge privacy',
    desc: 'Built on Midnight Network. Every trade is a ZK proof. Your wallet balances and trading activity stay private by default.',
    icon: (
      <svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5">
        <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z" />
      </svg>
    ),
  },
  {
    title: 'No rugs, no insiders',
    desc: 'Fair launch only. No presale, no team tokens, no hidden allocations. The bonding curve is the only way to get tokens — same rules for everyone.',
    icon: (
      <svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5">
        <path d="M9 12l2 2 4-4" /><circle cx="12" cy="12" r="10" />
      </svg>
    ),
  },
  {
    title: 'Instant liquidity',
    desc: 'The bonding curve acts as an automated market maker from the first trade. Buy and sell instantly — no need to wait for someone on the other side.',
    icon: (
      <svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5">
        <path d="M12 2v20M2 12h20" />
      </svg>
    ),
  },
  {
    title: 'Dev rev share',
    desc: 'Token creators earn a share of trading fees generated by their token. The more your community trades, the more you earn — aligned incentives for builders.',
    icon: (
      <svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5">
        <path d="M12 1v4M12 19v4M4.93 4.93l2.83 2.83M16.24 16.24l2.83 2.83M1 12h4M19 12h4M4.93 19.07l2.83-2.83M16.24 7.76l2.83-2.83" />
      </svg>
    ),
  },
  {
    title: 'Dust-free trading',
    desc: 'Connect with the 1AM wallet and trade without holding any DUST for gas fees. The wallet\'s ProofStation sponsors all network fees — you just trade.',
    icon: (
      <svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5">
        <path d="M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4M17 8l-5-5-5 5M12 3v12" />
      </svg>
    ),
  },
  {
    title: 'Permanent liquidity',
    desc: 'When a token graduates, LP tokens are burned. The DEX pool can never be drained — liquidity is locked forever, protecting holders.',
    icon: (
      <svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5">
        <rect x="3" y="11" width="18" height="11" rx="2" /><path d="M7 11V7a5 5 0 0110 0v4" />
      </svg>
    ),
  },
];

export default function HowItWorksPage() {
  return (
    <div style={{ flex: 1, overflowY: 'auto' }}>
      <div style={{ maxWidth: 900, margin: '0 auto', padding: '52px 31px 104px' }}>

        {/* Hero */}
        <div style={{ textAlign: 'center', marginBottom: 60 }}>
          <img src="/logo.png" alt="stfu.fun" style={{ width: 100, height: 100, marginBottom: 20 }} />
          <h1 style={{ fontSize: 40, fontWeight: 700, letterSpacing: '-0.03em', marginBottom: 12 }}>
            How <span style={{ color: '#0070f3' }}>stfu.fun</span> works
          </h1>
          <p style={{ fontSize: 18, color: 'var(--text-secondary)', maxWidth: 560, margin: '0 auto', lineHeight: 1.6 }}>
            The fairest way to launch tokens on Midnight. No presale, no insiders — just a bonding curve and ZK privacy.
          </p>
        </div>

        {/* Steps */}
        <div style={{ marginBottom: 60 }}>
          {STEPS.map((step, i) => (
            <div key={step.num} style={{
              display: 'flex', gap: 20, marginBottom: i < STEPS.length - 1 ? 0 : 0,
              position: 'relative', paddingBottom: i < STEPS.length - 1 ? 40 : 0,
            }}>
              {/* Line connector */}
              {i < STEPS.length - 1 && (
                <div style={{
                  position: 'absolute', left: 23, top: 48, bottom: 0, width: 1,
                  background: 'var(--border-color)',
                }} />
              )}
              {/* Number */}
              <div style={{
                width: 48, height: 48, borderRadius: '50%', flexShrink: 0,
                border: '2px solid var(--border-color-hover)',
                display: 'flex', alignItems: 'center', justifyContent: 'center',
                fontFamily: 'var(--mono)', fontSize: 18, fontWeight: 700,
                color: 'var(--text-primary)', background: 'var(--bg-secondary)',
                position: 'relative', zIndex: 1,
              }}>
                {step.num}
              </div>
              {/* Content */}
              <div style={{ flex: 1, paddingTop: 4 }}>
                <h3 style={{ fontSize: 20, fontWeight: 700, marginBottom: 8 }}>{step.title}</h3>
                <p style={{ fontSize: 16, color: 'var(--text-secondary)', lineHeight: 1.6 }}>{step.desc}</p>
              </div>
            </div>
          ))}
        </div>

        {/* Features grid */}
        <div style={{ marginBottom: 60 }}>
          <h2 style={{ fontSize: 28, fontWeight: 700, letterSpacing: '-0.02em', marginBottom: 8, textAlign: 'center' }}>
            Why stfu.fun
          </h2>
          <p style={{ fontSize: 16, color: 'var(--text-secondary)', textAlign: 'center', marginBottom: 32 }}>
            Privacy-first token launches powered by zero-knowledge proofs.
          </p>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(min(100%, 260px), 1fr))', gap: 16 }}>
            {FEATURES.map(f => (
              <div key={f.title} className="glass" style={{
                padding: '24px 22px', borderRadius: 'var(--radius-md)',
              }}>
                <div style={{ marginBottom: 14, color: '#0070f3' }}>{f.icon}</div>
                <h4 style={{ fontSize: 17, fontWeight: 700, marginBottom: 8 }}>{f.title}</h4>
                <p style={{ fontSize: 14, color: 'var(--text-secondary)', lineHeight: 1.6 }}>{f.desc}</p>
              </div>
            ))}
          </div>
        </div>

        {/* Rev share callout */}
        <div className="glass" style={{
          padding: '32px 28px', borderRadius: 'var(--radius-lg)', marginBottom: 60,
          border: '1px solid rgba(0, 112, 243, 0.25)',
          background: 'rgba(0, 112, 243, 0.04)',
        }}>
          <h3 style={{ fontSize: 22, fontWeight: 700, marginBottom: 10 }}>
            Earn from your token
          </h3>
          <p style={{ fontSize: 16, color: 'var(--text-secondary)', lineHeight: 1.7, marginBottom: 16 }}>
            Every trade on your token generates a <strong style={{ color: 'var(--text-primary)' }}>1% fee</strong>. As the creator, you receive a
            <strong style={{ color: '#0070f3' }}> revenue share</strong> of all trading fees — paid automatically to your wallet in NIGHT. No claims, no vesting, no lockups.
          </p>
          <p style={{ fontSize: 16, color: 'var(--text-secondary)', lineHeight: 1.7 }}>
            The more your community trades, the more you earn. Build a token people want to trade and get paid for it — forever.
          </p>
        </div>

        {/* Fees */}
        <div style={{ marginBottom: 60 }}>
          <h2 style={{ fontSize: 28, fontWeight: 700, letterSpacing: '-0.02em', marginBottom: 24, textAlign: 'center' }}>Fees</h2>
          <div className="glass" style={{ borderRadius: 'var(--radius-md)', overflow: 'hidden' }}>
            {[
              ['Token creation', 'Free', 'No cost to launch a token'],
              ['Trading fee', '1%', 'Applied on each buy and sell'],
              ['Creator rev share', 'Portion of 1% fee', 'Paid to token creator per trade'],
              ['Network gas', 'Sponsored', 'Free with 1AM wallet via ProofStation'],
              ['Graduation', 'Automatic', 'At 320,000 NIGHT reserve, LP burned on NorthStar'],
            ].map(([label, value, note], i, arr) => (
              <div key={label} style={{
                display: 'flex', alignItems: 'center', padding: '16px 22px', gap: 16,
                borderBottom: i < arr.length - 1 ? '1px solid var(--border-color)' : 'none',
                flexWrap: 'wrap',
              }}>
                <span style={{ flex: 1, fontSize: 16, fontWeight: 600, minWidth: 140 }}>{label}</span>
                <span style={{ fontFamily: 'var(--mono)', fontSize: 16, fontWeight: 700, color: '#0070f3', minWidth: 120 }}>{value}</span>
                <span style={{ fontSize: 14, color: 'var(--text-tertiary)', flex: '1 1 100%' }}>{note}</span>
              </div>
            ))}
          </div>
        </div>

        {/* CTA */}
        <div style={{ textAlign: 'center' }}>
          <Link href="/launch">
            <button className="btn btn-primary" style={{
              height: 57, fontSize: 18, padding: '0 42px', borderRadius: 'var(--radius-pill)',
              background: '#0070f3', color: '#ffffff',
            }}>
              Launch your token
            </button>
          </Link>
          <p style={{ fontSize: 14, color: 'var(--text-tertiary)', marginTop: 14 }}>
            No code required. Takes 30 seconds.
          </p>
        </div>
      </div>
    </div>
  );
}
