/**
 * night.fun — Deploy Script (Preprod)
 *
 * Usage:
 *   npm run deploy
 *
 * This follows the exact pattern from the create-mn-app counter example.
 * It:
 *   1. Creates or restores a headless wallet
 *   2. Funds check via Preprod faucet
 *   3. Deploys the bonding_curve contract
 *   4. Saves contract address to deployment.json
 *
 * Prerequisites:
 *   - Docker running (proof server)
 *   - npm run start-proof-server (in a separate terminal)
 *   - Wallet funded from https://faucet.preprod.midnight.network/
 */

import * as readline from 'readline/promises';
import * as fs from 'fs/promises';
import * as path from 'path';
import { fileURLToPath } from 'url';
import * as crypto from 'crypto';

// ── Midnight SDK imports ──────────────────────────────────────────────────────
// These are the real package names from the compatibility matrix:
// Midnight.js 3.1.0, Compact JS 2.4.0, Wallet SDK 1.0.0
import { NetworkId } from '@midnight-ntwrk/midnight-js-network-id';
import { createLogger } from '@midnight-ntwrk/midnight-js-utils';
// The compiled contract types (generated by: compact compile contracts/bonding_curve.compact)
// import type { BondingCurveContract } from '../contracts/managed/bonding_curve/contract/index.cjs';

// ── Config ────────────────────────────────────────────────────────────────────

const PREPROD_CONFIG = {
  networkId:       NetworkId.TestNet,
  nodeUri:         'https://rpc.preprod.midnight.network',
  indexerUri:      'https://indexer.preprod.midnight.network/api/v3/graphql',
  indexerWsUri:    'wss://indexer.preprod.midnight.network/api/v3/graphql/ws',
  proverServerUri: 'http://localhost:6300',    // local Docker proof server
  // OR use the hosted Preprod proof server:
  // proverServerUri: 'https://lace-proof-pub.preprod.midnight.network',
};

const DEPLOYMENT_FILE = path.resolve(process.cwd(), 'deployment.json');
const __dirname = path.dirname(fileURLToPath(import.meta.url));

// ── Treasury key (generate once, store securely) ──────────────────────────────

function generateTreasuryKey(): string {
  return crypto.randomBytes(32).toString('hex');
}

async function getTreasuryKey(): Promise<string> {
  try {
    const deployment = JSON.parse(await fs.readFile(DEPLOYMENT_FILE, 'utf-8'));
    if (deployment.treasuryKey) return deployment.treasuryKey;
  } catch {}
  // First run: generate and save
  const key = generateTreasuryKey();
  console.log('\n⚠️  Generated treasury key. Save this securely:\n', key, '\n');
  return key;
}

// ── Wallet setup ──────────────────────────────────────────────────────────────

async function setupWallet(rl: readline.Interface) {
  console.log('\n─────────────────────────────────────');
  console.log('  Wallet Setup');
  console.log('─────────────────────────────────────');
  console.log('[1] Create a new wallet');
  console.log('[2] Restore wallet from seed');
  console.log('[3] Exit');

  const choice = await rl.question('\n> ');

  if (choice === '3') process.exit(0);

  if (choice === '1') {
    // Generate new wallet seed
    const seed = crypto.randomBytes(32).toString('hex');
    console.log('\n⚠️  SAVE YOUR SEED PHRASE:');
    console.log('  Seed:', seed);
    console.log('\n  Fund your wallet from the Preprod faucet:');
    console.log('  https://faucet.preprod.midnight.network/\n');

    // TODO: initialize headless wallet with Wallet SDK 1.0.0
    // import { initWallet } from '@midnight-ntwrk/wallet-sdk';
    // const wallet = await initWallet({ seed, network: PREPROD_CONFIG.networkId, ... });
    return { seed };
  }

  if (choice === '2') {
    const seed = await rl.question('  Enter your wallet seed: ');
    console.log('  ✓ Restoring wallet...');

    // TODO: restore headless wallet
    // const wallet = await restoreWallet({ seed, network: PREPROD_CONFIG.networkId, ... });
    return { seed: seed.trim() };
  }

  throw new Error('Invalid choice');
}

// ── Deploy bonding curve ──────────────────────────────────────────────────────

interface DeployParams {
  tokenName:    string;
  ticker:       string;
  description:  string;
  imageIpfsUri: string;
  initialBuy:   bigint;    // tDUST (0 = no initial buy)
  treasuryKey:  string;    // hex 32 bytes
  creatorSeed:  string;    // wallet seed hex
}

interface DeployResult {
  contractAddress: string;
  txHash:          string;
  deployedAt:      number;
}

async function deployBondingCurve(params: DeployParams): Promise<DeployResult> {
  const {
    tokenName, ticker, description, imageIpfsUri,
    initialBuy, treasuryKey, creatorSeed,
  } = params;

  console.log('\n  ⠋ Deploying bonding curve contract...');

  // Hash metadata for on-chain storage
  const nameHash        = sha256(tokenName);
  const tickerHash      = sha256(ticker);
  const descHash        = sha256(description);
  const imageHash       = sha256(imageIpfsUri);
  const treasuryKeyBuf  = Buffer.from(treasuryKey, 'hex');

  console.log('  Metadata hashes computed');
  console.log('  Initial buy:', initialBuy.toString(), 'tDUST');

  // ── REAL DEPLOY FLOW (Midnight.js 3.1.0 + Compact JS 2.4.0) ────────────────
  //
  // After running: compact compile contracts/bonding_curve.compact contracts/managed/bonding_curve
  // The compiler generates TypeScript bindings at:
  //   contracts/managed/bonding_curve/contract/index.cjs
  //
  // The pattern (based on create-mn-app counter example) is:
  //
  //   import { Contract } from '../contracts/managed/bonding_curve/contract/index.cjs';
  //   import { midnight } from '@midnight-ntwrk/midnight-js-types';
  //   import { deployContract } from '@midnight-ntwrk/midnight-js-contracts';
  //   import { createBuilders } from '@midnight-ntwrk/midnight-js-contract-builders';
  //
  //   // Set up providers (node, indexer, proof server)
  //   const providers = await setupProviders({
  //     nodeUri:         PREPROD_CONFIG.nodeUri,
  //     indexerUri:      PREPROD_CONFIG.indexerUri,
  //     indexerWsUri:    PREPROD_CONFIG.indexerWsUri,
  //     proverServerUri: PREPROD_CONFIG.proverServerUri,
  //     walletSeed:      creatorSeed,
  //   });
  //
  //   // Deploy with constructor args
  //   const { contractAddress, deployTx } = await deployContract(providers, {
  //     contract: Contract,
  //     privateStateKey: 'night_fun_curve',
  //     initialPrivateState: {
  //       creatorSecretKey: () => Buffer.from(creatorSeed, 'hex').slice(0, 32),
  //       treasurySecretKey: () => Buffer.from(treasuryKey, 'hex'),
  //     },
  //     args: {
  //       creator_sk:    Buffer.from(creatorSeed, 'hex').slice(0, 32),
  //       treasury_key:  treasuryKeyBuf,
  //       name_h:        nameHash,
  //       ticker_h:      tickerHash,
  //       description_h: descHash,
  //       image_h:       imageHash,
  //       initial_ada:   initialBuy,
  //     },
  //   });
  //
  //   return { contractAddress, txHash: deployTx.hash, deployedAt: Date.now() };
  // ──────────────────────────────────────────────────────────────────────────

  // STUB (remove once SDK is wired):
  const mockAddress = '0x' + crypto.randomBytes(32).toString('hex');
  const mockTxHash  = '0x' + crypto.randomBytes(32).toString('hex');

  console.log('\n  ✅ Contract deployed!');
  console.log('  Address:', mockAddress);
  console.log('  Tx:     ', mockTxHash);
  console.log('\n  NOTE: Stub deployment — wire real SDK to activate.\n');

  return { contractAddress: mockAddress, txHash: mockTxHash, deployedAt: Date.now() };
}

// ── Main ──────────────────────────────────────────────────────────────────────

async function main() {
  console.log('╔══════════════════════════════════════════════════════╗');
  console.log('║                                                      ║');
  console.log('║          night.fun — Token Deployer (Preprod)       ║');
  console.log('║                                                      ║');
  console.log('╚══════════════════════════════════════════════════════╝\n');

  const rl = readline.createInterface({ input: process.stdin, output: process.stdout });

  try {
    const { seed } = await setupWallet(rl);
    const treasuryKey = await getTreasuryKey();

    // Collect token info
    console.log('\n─────────────────────────────────────');
    console.log('  Token Info');
    console.log('─────────────────────────────────────');
    const tokenName    = await rl.question('  Token name: ');
    const ticker       = (await rl.question('  Ticker (e.g. MCAT): ')).toUpperCase();
    const description  = await rl.question('  Description: ');
    const imageUri     = await rl.question('  Image IPFS URI (or leave blank): ');
    const initialBuyStr = await rl.question('  Initial buy in DUST (0 = none): ');
    const initialBuy   = BigInt(Math.floor(parseFloat(initialBuyStr || '0') * 1e6));

    const result = await deployBondingCurve({
      tokenName,
      ticker,
      description,
      imageIpfsUri: imageUri || 'ipfs://',
      initialBuy,
      treasuryKey,
      creatorSeed: seed,
    });

    // Save deployment
    const deployment = {
      contractAddress: result.contractAddress,
      txHash:          result.txHash,
      deployedAt:      result.deployedAt,
      network:         'preprod',
      tokenName,
      ticker,
      treasuryKey,
      walletSeed:      seed,
    };

    await fs.writeFile(DEPLOYMENT_FILE, JSON.stringify(deployment, null, 2));
    console.log('  Saved to deployment.json');

  } finally {
    rl.close();
  }
}

main().catch(err => {
  console.error('\n❌ Deploy failed:', err.message);
  process.exit(1);
});

// ── Helpers ───────────────────────────────────────────────────────────────────

function sha256(data: string): Buffer {
  return crypto.createHash('sha256').update(data).digest();
}
